#ifndef DIFFUSION_PLATFORM_WIN32_TYPES_H
#define DIFFUSION_PLATFORM_WIN32_TYPES_H

#define WIN32_LEAN_AND_MEAN
#define UNICODE
#define _UNICODE
#include <Windows.h>

#endif // DIFFUSION_PLATFORM_WIN32_TYPES_H
