name: Build and Test

on:
  push:
    branches: [ "*" ]

env:
  # Cmake build type
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspaces}}\build
        run: ctest -C ${{env.BUILD_TYPE}}