name: Build and Test

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSVC native toolchain
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
      - name: Configure CMake
        run: cmake --preset release
      - name: Build
        run: cmake --build --preset all-release
      - name: Test
        run: ctest --preset release